-- ============================================================================
-- Database Schema: expenzo_v2
-- Target : PostgreSQL
-- Schema: expenzo_v2
-- ============================================================================

-- Schema creation (run if not already present)
-- CREATE SCHEMA IF NOT EXISTS expenzo_v2;
-- SET search_path TO expenzo_v2;

-- ============================================================================
-- Table: expenzo_user
-- Description: Stores user account information for authentication and profile
-- ============================================================================

CREATE TABLE IF NOT EXISTS expenzo_user (
    id              VARCHAR(36)    PRIMARY KEY,                          -- UUID (auto-generated by JPA)
    email           VARCHAR(255)   NOT NULL UNIQUE,                      -- Login identifier, must be unique
    first_name      VARCHAR(100)   NOT NULL,                             -- Required first name
    last_name       VARCHAR(100),                                        -- Optional last name
    country_code    VARCHAR(5),                                          -- e.g., "+1", "+91"
    mobile_number   VARCHAR(20),                                         -- Mobile phone number
    password        VARCHAR(255)   NOT NULL                              -- BCrypt-hashed password
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_expenzo_user_email ON expenzo_user (email);
