-- =============================================================================
-- Table: bank
-- Description: Reference table containing the list of supported banks.
--              Managed by the system; users do not create bank records directly.
-- =============================================================================

CREATE TABLE bank (
    id         VARCHAR(36)  NOT NULL PRIMARY KEY,
    name       VARCHAR(100) NOT NULL UNIQUE,
    short_name VARCHAR(25)  NOT NULL UNIQUE
);

COMMENT ON TABLE  bank            IS 'System-managed reference list of banks';
COMMENT ON COLUMN bank.id         IS 'UUID primary key — generated by the service layer';
COMMENT ON COLUMN bank.name       IS 'Full official name of the bank (e.g. Housing Development Finance Corporation)';
COMMENT ON COLUMN bank.short_name IS 'Abbreviated name shown in UI (e.g. HDFC, SBI)';
