-- =============================================================================
-- Table: bank_account
-- Description: Represents a user's bank account. Both debit cards and credit
--              cards reference this table to indicate which bank issued them.
-- Dependencies: user, bank
-- =============================================================================

CREATE TYPE account_type_enum AS ENUM ('SAVINGS', 'CURRENT');

CREATE TABLE bank_account (
    id             VARCHAR(36)       NOT NULL PRIMARY KEY,
    user_id        VARCHAR(36)       NOT NULL,
    bank_id        VARCHAR(36)       NOT NULL,
    account_type   account_type_enum NOT NULL,
    account_number VARCHAR(50)       NOT NULL UNIQUE,
    nick_name      VARCHAR(50),
    created_at     TIMESTAMPTZ       NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ       NOT NULL DEFAULT now(),
    is_active      BOOLEAN           NOT NULL DEFAULT TRUE,
    deleted_at     TIMESTAMPTZ,

    CONSTRAINT fk_bank_account_user FOREIGN KEY (user_id) REFERENCES expenzo_user (id),
    CONSTRAINT fk_bank_account_bank FOREIGN KEY (bank_id) REFERENCES bank (id)
);

CREATE INDEX idx_bank_account_user_id ON bank_account (user_id);

COMMENT ON TABLE  bank_account                IS 'User bank accounts';
COMMENT ON COLUMN bank_account.id             IS 'UUID primary key — generated by the service layer';
COMMENT ON COLUMN bank_account.user_id        IS 'FK → user.id — owner of the account';
COMMENT ON COLUMN bank_account.bank_id        IS 'FK → bank.id — issuing bank';
COMMENT ON COLUMN bank_account.account_type   IS 'SAVINGS or CURRENT';
COMMENT ON COLUMN bank_account.account_number IS 'Full account number — store encrypted at rest';
COMMENT ON COLUMN bank_account.nick_name      IS 'User-defined label (e.g. "Salary account")';
COMMENT ON COLUMN bank_account.created_at     IS 'Record creation timestamp';
COMMENT ON COLUMN bank_account.updated_at     IS 'Last update timestamp';
COMMENT ON COLUMN bank_account.is_active      IS 'Whether the account is currently active';
COMMENT ON COLUMN bank_account.deleted_at     IS 'Soft-delete timestamp; NULL = not deleted';
