-- =============================================================================
-- Table: credit_card
-- Description: Stores credit cards. bank_account_id is optional — a user may
--              add a standalone credit card not linked to any bank account in
--              the system. credit_limit and billing_date drive dashboard
--              utilisation widgets.
-- Dependencies: user, bank_account (optional)
-- =============================================================================

CREATE TABLE credit_card (
    id              VARCHAR(36)    NOT NULL PRIMARY KEY,
    user_id         VARCHAR(36)    NOT NULL,
    bank_account_id VARCHAR(36),
    card_number     VARCHAR(19)    NOT NULL UNIQUE,
    valid_from      DATE           NOT NULL,
    valid_to        DATE           NOT NULL,
    credit_limit    NUMERIC(12, 2) NOT NULL CHECK (credit_limit > 0),
    billing_date    SMALLINT       NOT NULL CHECK (billing_date BETWEEN 1 AND 28),
    nick_name       VARCHAR(50),
    created_at      TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ    NOT NULL DEFAULT now(),
    is_active       BOOLEAN        NOT NULL DEFAULT TRUE,
    deleted_at      TIMESTAMPTZ,

    CONSTRAINT fk_credit_card_user         FOREIGN KEY (user_id)         REFERENCES expenzo_user (id),
    CONSTRAINT fk_credit_card_bank_account FOREIGN KEY (bank_account_id) REFERENCES bank_account (id),
    CONSTRAINT chk_credit_card_validity    CHECK (valid_to > valid_from)
);

CREATE INDEX idx_credit_card_user_id ON credit_card (user_id);

COMMENT ON TABLE  credit_card                  IS 'Credit cards — may be standalone or linked to a bank account';
COMMENT ON COLUMN credit_card.id               IS 'UUID primary key — generated by the service layer';
COMMENT ON COLUMN credit_card.user_id          IS 'FK → user.id — card holder';
COMMENT ON COLUMN credit_card.bank_account_id  IS 'FK → bank_account.id — nullable; NULL for standalone cards';
COMMENT ON COLUMN credit_card.card_number      IS 'Full 16–19 digit card number — store encrypted at rest';
COMMENT ON COLUMN credit_card.valid_from       IS 'Card validity start date (month/year)';
COMMENT ON COLUMN credit_card.valid_to         IS 'Card expiry date (month/year)';
COMMENT ON COLUMN credit_card.credit_limit     IS 'Approved credit limit in the user currency';
COMMENT ON COLUMN credit_card.billing_date     IS 'Day of month the billing cycle closes (1–28)';
COMMENT ON COLUMN credit_card.nick_name        IS 'User-defined label (e.g. "HDFC Regalia")';
COMMENT ON COLUMN credit_card.created_at       IS 'Record creation timestamp';
COMMENT ON COLUMN credit_card.updated_at       IS 'Last update timestamp';
COMMENT ON COLUMN credit_card.is_active        IS 'Whether the card is currently active';
COMMENT ON COLUMN credit_card.deleted_at       IS 'Soft-delete timestamp; NULL = not deleted';
