-- =============================================================================
-- Table: debit_card
-- Description: Stores debit cards belonging to a user. Each debit card must
--              be linked to an existing bank account held by the same user.
-- Dependencies: user, bank_account
-- =============================================================================

CREATE TABLE debit_card (
    id              VARCHAR(36) NOT NULL PRIMARY KEY,
    user_id         VARCHAR(36) NOT NULL,
    bank_account_id VARCHAR(36) NOT NULL,
    card_number     VARCHAR(19) NOT NULL UNIQUE,
    valid_from      DATE        NOT NULL,
    valid_to        DATE        NOT NULL,
    nick_name       VARCHAR(50),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    is_active       BOOLEAN     NOT NULL DEFAULT TRUE,
    deleted_at      TIMESTAMPTZ,

    CONSTRAINT fk_debit_card_user         FOREIGN KEY (user_id)         REFERENCES expenzo_user (id),
    CONSTRAINT fk_debit_card_bank_account FOREIGN KEY (bank_account_id) REFERENCES bank_account (id),
    CONSTRAINT chk_debit_card_validity    CHECK (valid_to > valid_from)
);

CREATE INDEX idx_debit_card_user_id ON debit_card (user_id);

COMMENT ON TABLE  debit_card                  IS 'Debit cards linked to user bank accounts';
COMMENT ON COLUMN debit_card.id               IS 'UUID primary key — generated by the service layer';
COMMENT ON COLUMN debit_card.user_id          IS 'FK → user.id — card holder';
COMMENT ON COLUMN debit_card.bank_account_id  IS 'FK → bank_account.id — linked bank account';
COMMENT ON COLUMN debit_card.card_number      IS 'Full 16–19 digit card number — store encrypted at rest';
COMMENT ON COLUMN debit_card.valid_from       IS 'Card validity start date (month/year)';
COMMENT ON COLUMN debit_card.valid_to         IS 'Card expiry date (month/year)';
COMMENT ON COLUMN debit_card.nick_name        IS 'User-defined label (e.g. "My HDFC Debit")';
COMMENT ON COLUMN debit_card.created_at       IS 'Record creation timestamp';
COMMENT ON COLUMN debit_card.updated_at       IS 'Last update timestamp';
COMMENT ON COLUMN debit_card.is_active        IS 'Whether the card is currently active';
COMMENT ON COLUMN debit_card.deleted_at       IS 'Soft-delete timestamp; NULL = not deleted';
