-- =============================================================================
-- Table: payment_channel
-- Description: Polymorphic wrapper that represents any payment instrument a
--              user owns — bank account, debit card, or credit card.
--              Transactions always reference payment_channel, never the
--              underlying instrument table directly.
--
--              channel_id is a soft FK — its target table is determined by
--              channel_type. Referential integrity is enforced at the
--              application layer.
-- Dependencies: user
-- =============================================================================

CREATE TYPE payment_channel_type_enum AS ENUM (
    'BANK_ACCOUNT',
    'DEBIT_CARD',
    'CREDIT_CARD'
);

CREATE TABLE payment_channel (
    id           VARCHAR(36)               NOT NULL PRIMARY KEY,
    user_id      VARCHAR(36)               NOT NULL,
    channel_type payment_channel_type_enum NOT NULL,
    channel_id   VARCHAR(36)               NOT NULL,
    created_at   TIMESTAMPTZ               NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ               NOT NULL DEFAULT now(),
    is_active    BOOLEAN                   NOT NULL DEFAULT TRUE,
    deleted_at   TIMESTAMPTZ,

    CONSTRAINT fk_payment_channel_user       FOREIGN KEY (user_id) REFERENCES expenzo_user (id),
    CONSTRAINT uq_payment_channel_instrument UNIQUE (user_id, channel_type, channel_id)
);

CREATE INDEX idx_payment_channel_user_id ON payment_channel (user_id);

COMMENT ON TABLE  payment_channel              IS 'Polymorphic pointer to any payment instrument owned by a user';
COMMENT ON COLUMN payment_channel.id           IS 'UUID primary key — generated by the service layer';
COMMENT ON COLUMN payment_channel.user_id      IS 'FK → user.id — owner of this channel';
COMMENT ON COLUMN payment_channel.channel_type IS 'Discriminator: BANK_ACCOUNT | DEBIT_CARD | CREDIT_CARD';
COMMENT ON COLUMN payment_channel.channel_id   IS 'Soft FK to bank_account.id, debit_card.id, or credit_card.id — resolved via channel_type';
COMMENT ON COLUMN payment_channel.created_at   IS 'Record creation timestamp';
COMMENT ON COLUMN payment_channel.updated_at   IS 'Last update timestamp';
COMMENT ON COLUMN payment_channel.is_active    IS 'Whether this channel is available for use in transactions';
COMMENT ON COLUMN payment_channel.deleted_at   IS 'Soft-delete timestamp; NULL = not deleted';
