-- =============================================================================
-- Table: transaction
-- Description: The core financial record. Every money movement — expense,
--              income, self-transfer, or investment — is stored here.
--              dest_channel is only populated for SELF_TRANSFER transactions.
-- Dependencies: user, payment_channel
-- =============================================================================

CREATE TABLE transaction (
    id             VARCHAR(36)           NOT NULL PRIMARY KEY,
    user_id        VARCHAR(36)           NOT NULL,
    spend_on       TIMESTAMPTZ           NOT NULL,
    amount         NUMERIC(12, 2)        NOT NULL CHECK (amount > 0),
    title          VARCHAR(100)          NOT NULL,
    notes          VARCHAR(255),
    type           VARCHAR(15)    NOT NULL CHECK (type IN ('EXPENSE', 'INCOME', 'SELF_TRANSFER', 'INVESTMENT')),
    source_channel VARCHAR(36)           NOT NULL,
    dest_channel   VARCHAR(36),
    created_at     TIMESTAMPTZ           NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ           NOT NULL DEFAULT now(),
    is_active      BOOLEAN               NOT NULL DEFAULT TRUE,
    deleted_at     TIMESTAMPTZ,

    CONSTRAINT fk_transaction_user           FOREIGN KEY (user_id)        REFERENCES expenzo_user (id),
    CONSTRAINT fk_transaction_source_channel FOREIGN KEY (source_channel) REFERENCES payment_channel (id),
    CONSTRAINT fk_transaction_dest_channel   FOREIGN KEY (dest_channel)   REFERENCES payment_channel (id),

    CONSTRAINT chk_transaction_dest_channel CHECK (
        (type = 'SELF_TRANSFER' AND dest_channel IS NOT NULL)
        OR
        (type <> 'SELF_TRANSFER' AND dest_channel IS NULL)
    )
);

CREATE INDEX idx_transaction_user_id ON transaction (user_id);

COMMENT ON TABLE  transaction                IS 'Core financial records — expense, income, self-transfer, investment';
COMMENT ON COLUMN transaction.id             IS 'UUID primary key — generated by the service layer';
COMMENT ON COLUMN transaction.user_id        IS 'FK → user.id — owner of the transaction';
COMMENT ON COLUMN transaction.spend_on       IS 'Date and time the transaction occurred (user-supplied, stored in UTC)';
COMMENT ON COLUMN transaction.amount         IS 'Always positive; sign implied by type (EXPENSE/SELF_TRANSFER = debit, INCOME = credit)';
COMMENT ON COLUMN transaction.title          IS 'Short description or merchant name';
COMMENT ON COLUMN transaction.notes          IS 'Optional longer note or memo';
COMMENT ON COLUMN transaction.type           IS 'EXPENSE | INCOME | SELF_TRANSFER | INVESTMENT';
COMMENT ON COLUMN transaction.source_channel IS 'FK → payment_channel.id — channel debited or credited';
COMMENT ON COLUMN transaction.dest_channel   IS 'FK → payment_channel.id — destination for SELF_TRANSFER only; NULL otherwise';
COMMENT ON COLUMN transaction.created_at     IS 'Record creation timestamp';
COMMENT ON COLUMN transaction.updated_at     IS 'Last update timestamp';
COMMENT ON COLUMN transaction.is_active      IS 'Logical active flag';
COMMENT ON COLUMN transaction.deleted_at     IS 'Soft-delete timestamp; NULL = not deleted';
